export const FOOTER_STRINGS = {
  en: {
    getin: "Get Connected",
    dontmiss: "Subscribe now and never miss the best offers",
    mail: "Your email",
    subscribe: "Subscribe",
    pages: "Pages",
    help: "Support",
    faq: "FAQ",
    terms: "Terms",
    privacy: "Privacy",
    social: "Follow us",
    bottom: "© American Soft Inc. 2025 — All rights reserved.",
    navPages: [
      { label: "Company", href: "#" },
      { label: "Android App", href: "#" },
      { label: "iOS App", href: "#" },
      { label: "Desktop", href: "#" },
      { label: "Projects", href: "#" },
      { label: "My tasks", href: "#" },
    ],
    langBtn: "AR",
    dir: "ltr",
  },
  ar: {
    getin: "تواصل معنا",
    dontmiss: "اشترك الآن ولا تفوّت أفضل العروض",
    mail: "بريدك الإلكتروني",
    subscribe: "اشترك",
    pages: "صفحات",
    help: "الدعم",
    faq: "الأسئلة الشائعة",
    terms: "الشروط",
    privacy: "الخصوصية",
    social: "تابعنا",
    bottom: "© American Soft Inc. 2025 — جميع الحقوق محفوظة.",
    navPages: [
      { label: "الشركة", href: "#" },
      { label: "تطبيق أندرويد", href: "#" },
      { label: "تطبيق iOS", href: "#" },
      { label: "سطح المكتب", href: "#" },
      { label: "المشاريع", href: "#" },
      { label: "مهامي", href: "#" },
    ],
    langBtn: "EN",
    dir: "rtl",
  },
};
