export const FOOTER_STRINGS = {
  en: {
    getin: "Get Connected",
    dontmiss: "Subscribe now and never miss the best offers",
    mail: "Your email",
    subscribe: "Subscribe",
    pages: "Pages",
    help: "Support",
    faq: "FAQ",
    terms: "Terms",
    privacy: "Privacy",
    social: "Follow us",
    bottom: "© American Soft Inc. 2025 — All rights reserved.",
    navPages: [
      { label: "Company",     href: "/en/company" },
      { label: "Android App", href: "/en/android" },
      { label: "iOS App",     href: "/en/ios" },
      { label: "Desktop",     href: "/en/desktop" },
      { label: "Projects",    href: "/en/projects" },
      { label: "My tasks",    href: "/en/tasks" },
    ],
    langBtn: "AR",
    dir: "ltr",
  },
  ar: {
    getin: "تواصل معنا",
    dontmiss: "اشترك الآن ولا تفوّت أفضل العروض",
    mail: "بريدك الإلكتروني",
    subscribe: "اشترك",
    pages: "صفحات",
    help: "الدعم",
    faq: "الأسئلة الشائعة",
    terms: "الشروط",
    privacy: "الخصوصية",
    social: "تابعنا",
    bottom: "© American Soft Inc. 2025 — جميع الحقوق محفوظة.",
    navPages: [
      { label: "الشركة",        href: "/company" },
      { label: "تطبيق أندرويد", href: "/android" },
      { label: "تطبيق iOS",     href: "/ios" },
      { label: "سطح المكتب",    href: "/desktop" },
      { label: "المشاريع",      href: "/projects" },
      { label: "مهامي",         href: "/tasks" },
    ],
    langBtn: "EN",
    dir: "rtl",
  },
};
